id-prefix: "MAL"
infected-path: "./infected/"
false-positive-path: "./withdrawn/"
sources:
- id: "ossf-package-analysis"
  bucket: "gs://gosst-package-detection-osv?access_id=-"
  prefix: "confident/"
  lookback-entries: 10
- id: "ghsa-malware"
  alias-id: true
